variable app_image_name {}
variable app_name {}
variable app_port {}
variable app_version {}
variable dockerhub_password {}
variable dockerhub_username {}
variable domain {}
variable k8s_cluster_ca {}
variable k8s_cluster_host {}
variable k8s_cluster_token {}
variable postgres_database_name {}
variable postgres_host {}
variable postgres_port {}
variable vault_address {}
variable vault_authz_path {}
variable vault_postgres_secrets_path {}
variable vault_oauth2_path {}
variable vault_postgres_admin_role_name {}
variable vault_postgres_read_only_role_name {}
variable vault_postgres_read_write_role_name {}
variable vault_postgres_roles_path {}
variable vault_postgres_superuser_password_key {}
variable vault_root_token {}
