[tool.poetry]
name = "deployment"
version = "0.1.0"
description = ""
authors = ["Giulio Mecocci <gmecocci@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
