variable environment_name {}
variable app_name {}
variable app_version {}
variable dockerhub_password {}
variable domain {}
variable k8s_cluster_ca {}
variable k8s_host {}
variable k8s_token {}
variable postgres_host {}
variable postgres_port {}
variable postgres_superuser {}
variable postgres_superuser_password {}
variable vault_address {}
variable vault_root_token {}