apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helm
subjects:
  - kind: ServiceAccount
    name: helm
    namespace: kube-system
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: helm
  apiGroup: rbac.authorization.k8s.io
